// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserReq struct {
	Id int32 `json:"id"`
}

type GetUserResp struct {
	Id    int32  `json:"id"`
	Name  string `json:"name"`
	Mail  string `json:"mail"`
	Phone string `json:"phone"`
}
