// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userTestFieldNames          = builder.RawFieldNames(&UserTest{})
	userTestRows                = strings.Join(userTestFieldNames, ",")
	userTestRowsExpectAutoSet   = strings.Join(stringx.Remove(userTestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userTestRowsWithPlaceHolder = strings.Join(stringx.Remove(userTestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserTestIdPrefix    = "cache:userTest:id:"
	cacheUserTestNamePrefix  = "cache:userTest:name:"
	cacheUserTestPhonePrefix = "cache:userTest:phone:"
)

type (
	userTestModel interface {
		Insert(ctx context.Context, data *UserTest) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserTest, error)
		FindOneByName(ctx context.Context, name sql.NullString) (*UserTest, error)
		FindOneByPhone(ctx context.Context, phone string) (*UserTest, error)
		Update(ctx context.Context, data *UserTest) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserTestModel struct {
		sqlc.CachedConn
		table string
	}

	UserTest struct {
		Id       int64          `db:"id"`
		Name     sql.NullString `db:"name"`     // The username
		Password string         `db:"password"` // The user password
		Phone    string         `db:"phone"`    // The mobile phone number
		Gender   string         `db:"gender"`   // gender,malelfemalelunknown
		Nickname string         `db:"nickname"` // The nickname
		Type     int64          `db:"type"`     // The user type,O:normal,1:vip, for test golang keyword
		CreateAt sql.NullTime   `db:"create_at"`
		UpdateAt time.Time      `db:"update_at"`
	}
)

func newUserTestModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserTestModel {
	return &defaultUserTestModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_test`",
	}
}

func (m *defaultUserTestModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userTestIdKey := fmt.Sprintf("%s%v", cacheUserTestIdPrefix, id)
	userTestNameKey := fmt.Sprintf("%s%v", cacheUserTestNamePrefix, data.Name)
	userTestPhoneKey := fmt.Sprintf("%s%v", cacheUserTestPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userTestIdKey, userTestNameKey, userTestPhoneKey)
	return err
}

func (m *defaultUserTestModel) FindOne(ctx context.Context, id int64) (*UserTest, error) {
	userTestIdKey := fmt.Sprintf("%s%v", cacheUserTestIdPrefix, id)
	var resp UserTest
	err := m.QueryRowCtx(ctx, &resp, userTestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTestRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTestModel) FindOneByName(ctx context.Context, name sql.NullString) (*UserTest, error) {
	userTestNameKey := fmt.Sprintf("%s%v", cacheUserTestNamePrefix, name)
	var resp UserTest
	err := m.QueryRowIndexCtx(ctx, &resp, userTestNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", userTestRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTestModel) FindOneByPhone(ctx context.Context, phone string) (*UserTest, error) {
	userTestPhoneKey := fmt.Sprintf("%s%v", cacheUserTestPhonePrefix, phone)
	var resp UserTest
	err := m.QueryRowIndexCtx(ctx, &resp, userTestPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userTestRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTestModel) Insert(ctx context.Context, data *UserTest) (sql.Result, error) {
	userTestIdKey := fmt.Sprintf("%s%v", cacheUserTestIdPrefix, data.Id)
	userTestNameKey := fmt.Sprintf("%s%v", cacheUserTestNamePrefix, data.Name)
	userTestPhoneKey := fmt.Sprintf("%s%v", cacheUserTestPhonePrefix, data.Phone)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userTestRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Password, data.Phone, data.Gender, data.Nickname, data.Type)
	}, userTestIdKey, userTestNameKey, userTestPhoneKey)
	return ret, err
}

func (m *defaultUserTestModel) Update(ctx context.Context, newData *UserTest) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userTestIdKey := fmt.Sprintf("%s%v", cacheUserTestIdPrefix, data.Id)
	userTestNameKey := fmt.Sprintf("%s%v", cacheUserTestNamePrefix, data.Name)
	userTestPhoneKey := fmt.Sprintf("%s%v", cacheUserTestPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userTestRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Password, newData.Phone, newData.Gender, newData.Nickname, newData.Type, newData.Id)
	}, userTestIdKey, userTestNameKey, userTestPhoneKey)
	return err
}

func (m *defaultUserTestModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserTestIdPrefix, primary)
}

func (m *defaultUserTestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTestRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserTestModel) tableName() string {
	return m.table
}
